### ISSUE TITLE
Teacher Passwords

### ISSUE THREAD

**Issue by rennera** [RADB/Offord-EDI-2020#1]
We don’t want teachers to have the capability to change their password or username on the system. We want to keep our capabilities on the administrator side, but don’t want them to have access to do so.

**Comment by rennera** [comment]
password should be defaulted to 8 digits from the ediid
![image](https://user-images.githubusercontent.com/3689865/103856132-23b58000-5082-11eb-8cad-cbb4381b8fd1.png)

**Comment by blazornut** [comment]
done
