### ISSUE TITLE
Variables to add to data export

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#103]
Hey Andrew, 

The data pull from the older system included some variables that are not currently in the excel export from the new system. Can you add the following variables? 

-	Local ID number 
- 	Chk_completed (indicating questionnaire was locked)
-	Doc_edi (indicating date of completion)
-	Language_completed (indicating which language each section of the EDI was completed in)
-	Stud_id (indicating student ID)
-	class_id (indicating class ID)
-	Teacher_id (indicating teacher ID)
-	School_name (indicating School Name)
-	Sch_id (indicating school ID code)
-	Created_by (indicating if this student was added to the class list by teacher)

**Comment by rennera** [comment]
I should be able to add all of those fields.

 

I will have a look at this tonight.

 

From: rasope ***@***.*** 
Sent: Thursday, April 8, 2021 1:14 PM
To: RADB/Offord-EDI-2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RADB/Offord-EDI-2020] Variables to add to data export (#103)

 

Hey Andrew,

The data pull from the older system included some variables that are not currently in the excel export from the new system. Can you add the following variables?

*	Local ID number
*	Chk_completed (indicating questionnaire was locked)
*	Doc_edi (indicating date of completion)
*	Language_completed (indicating which language each section of the EDI was completed in)
*	Stud_id (indicating student ID)
*	class_id (indicating class ID)
*	Teacher_id (indicating teacher ID)
*	School_name (indicating School Name)
*	Sch_id (indicating school ID code)
*	Created_by (indicating if this student was added to the class list by teacher)

**Comment by rennera** [comment]
I have deployed this to production.

Included all fields as requested in addition to the province name.
