### ISSUE TITLE
Variables names to be updated

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#104]
Attached is a list of the new variables names we'd like imported to the e-edi system. 
[ReportData_variable names_PR.xlsx](https://github.com/RADB/Offord-EDI-2020/files/6427753/ReportData_variable.names_PR.xlsx)

**Comment by rennera** [comment]
All variable name changes have been pushed to production.

**Comment by rasope** [comment]
I'm getting this error message below when trying to generate a data file.

![image](https://user-images.githubusercontent.com/24963245/121055881-a8204200-c78b-11eb-9f94-644d84f8e428.png)

**Comment by rennera** [comment]
I changed my status column to StudentStatus - that is the one with the Locked etc

Also updated the by province to have the exact same header fields that we added to the original dataset
