### ISSUE TITLE
Class List Page

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#106]
-	Update overall appearance to less "Excel" style appearance.
-	Feedback that table spacing is non-consistent across users/bowsers.
-	Remove delete button from class list
-	Remove Year column from class list
-	Add webmaster@e-edi.ca contact information
![image](https://user-images.githubusercontent.com/24963245/118023832-00e6f100-b32c-11eb-8853-8fab0a55d0bf.png)

**Comment by rennera** [comment]
- [ ] Update overall appearance to less "Excel" style appearance.
- [ ] Feedback that table spacing is non-consistent across users/bowsers.
- [ ] Remove delete button from class list
- [ ] Remove Year column from class list
- [ ] Add webmaster@e-edi.ca contact information

- [ ]
