### ISSUE TITLE
e-EDI Questionnaire (General updates)

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#107]
-	Update general spacing of questions and response grid to a tighter format. The current appearance is not up to our standards. Teachers should see less blank space throughout the questionnaire. 
-	Remove the green “Save” pop-up that appears after every page. They tend to linger and can add on top of each other. 
-	Remove font size toggle. It only change the size of the question, not the response options. it's not intuitive. 
- 	Kick teachers out after 15 minutes of inactivity similar to previous system
- 	Remove Labels toggle. Remove header on questions and keep labels on all the time

**Comment by rennera** [comment]
- [ ] Update general spacing of questions and response grid to a tighter format. The current appearance is not up to our standards. Teachers should see less blank space throughout the questionnaire.
- [ ] Remove the green “Save” pop-up that appears after every page. They tend to linger and can add on top of each other.
- [ ] Remove font size toggle. It only change the size of the question, not the response options. it's not intuitive.
- [ ] Kick teachers out after 15 minutes of inactivity similar to previous system
- [ ] Remove Labels toggle. Remove header on questions and keep labels on all the time

**Comment by rennera** [comment]
Shortened the pop up duration and set it to disappear when navigating away from the page.
