### ISSUE TITLE
Demographics Section

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#108]
-	A bug exists after selecting language “Twi”. The questionnaire freezes. Does this occur for other languages?

**Comment by rennera** [comment]
Datatype will need to change to int.

**Comment by rennera** [comment]
`dotnet ef migrations add 2021DemographicsLanguageTypes --context servicecontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj -o Data/Migrations`

**Comment by rennera** [comment]
`dotnet ef database update -c servicecontext`

**Comment by rennera** [comment]
This has been deployed.
