### ISSUE TITLE
Teacher Profile

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#111]
- [x] -	Update language on question #6 to “If you did receive training, was it helpful?”
- [x] -	Spacing issue on teacher profile page needs to be addressed as well. Overall appearance can be improved.
- [x] -	Update Teacher Gender question responses to Male, Female, or Other.
- [ ] #125

**Comment by rennera** [comment]
The completed levels of education will require a schema change - I would recommend this for next year as your data collection is not quite complete.
