### ISSUE TITLE
Resources Page

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#112]
-	Can we update the appearance for how the resource PDFs are displayed? 

![image](https://user-images.githubusercontent.com/24963245/118026443-cb8fd280-b32e-11eb-9665-423eab3a730c.png)

**Comment by rennera** [comment]
Is this more like what you want?
![image](https://user-images.githubusercontent.com/3689865/121061599-0cde9b00-c792-11eb-9537-c3899d3ecb12.png)

**Comment by rennera** [comment]
This has been updated.
