### ISSUE TITLE
Unable to "unlock" on administrator side

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#150]
I’m unable to unlock any locked questionnaires at the moment. We have teachers completing today and they need some questionnaires unlocked. But the system won’t allow me to make the change. For example, I need 22013300010401 unlocked, and a few others in this class. Can you help?

**Comment by rennera** [comment]
All you need to do is navigate to the class list: Click the unlock image beside the status to unlock the questionnaire.  I have unlocked the one you specified.



 

 

 

From: rasope ***@***.*** 
Sent: Thursday, September 22, 2022 9:01 AM
To: RADB/Offord-EDI-2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RADB/Offord-EDI-2020] Unable to "unlock" on administrator side (Issue #150)

 

I’m unable to unlock any locked questionnaires at the moment. We have teachers completing today and they need some questionnaires unlocked. But the system won’t allow me to make the change. For example, I need 22013300010401 unlocked, and a few others in this class. Can you help?

**Comment by rasope** [comment]
Hey Andrew,

They are still displaying as locked. I just checked the class list again and noting is unlocked.

The system shows “unlocked”, but it doesn’t hold. When I refresh, or check the class list for the teacher’s side, all questionnaires remain locked.
***@***.***
--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University
(905) 525-9140 ext. 27051<tel:(905)%20525-9140;27051>  |  ***@***.******@***.***>
edi.offordcentre.com

**Comment by rennera** [comment]
Ok I will have a look at the code on that – that is odd!  

 

Can you send me the list you need unlocked and I will unlock them manually for now.

**Comment by rennera** [comment]
Hi Patricia,

 

I was able to correct this issue and the unlock holds as expected.



 

From: Andrew Renner ***@***.*** 
Sent: Thursday, September 22, 2022 11:19 AM
To: 'RADB/Offord-EDI-2020' ***@***.***>; 'RADB/Offord-EDI-2020' ***@***.***>
Cc: 'Comment' ***@***.***>
Subject: RE: [RADB/Offord-EDI-2020] Unable to "unlock" on administrator side (Issue #150)

 

Ok I will have a look at the code on that – that is odd!  

 

Can you send me the list you need unlocked and I will unlock them manually for now.

**Comment by rennera** [comment]
This functionality is now working as expected.
![image](https://user-images.githubusercontent.com/3689865/194057895-db3ba3e6-e6f3-4e1c-a1f5-391387b92d1e.png)

**Comment by rasope** [comment]
Thanks Andrew! 22013300010401, 02, 03 and 07


--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University 
1280
 Main Street West
MIP 201A,
 Hamilton, ON  L8S 4K1
(905)
 525-9140 ext. ***@***.***


On Sep 22, 2022, at 11:19 AM, rennera ***@***.***> wrote:




﻿

Ok I will have a look at the code on that – that is odd! 



Can you send me the list you need unlocked and I will unlock them manually for now.

**Comment by rennera** [comment]
All of these students have been unlocked.
