### ISSUE TITLE
2023 all provinces - Demographics Section

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#157]
-	Remove “What is the child's current format of instruction” question
-	Remove “Are you aware whether this child experienced any challenges with online instruction last year? (e.g. from your experience, told to you by parents or another teacher, etc).” question (this question is currently only in ON, NT, and NS)

**Comment by rennera** [comment]
- [ ] Remove “What is the child's current format of instruction” question
- [ ] Remove “Are you aware whether this child experienced any challenges with online instruction last year? (e.g. from your experience, told to you by parents or another teacher, etc).” question (this question is currently only in ON, NT, and NS)

**Comment by rennera** [comment]
Removed 1 from NFLD 2 was not present
