### ISSUE TITLE
2023 PEI – Demographics Section

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#158]
(All changes are based on current Newfoundland questionnaire)

Remove “Other” response option from sex question

Update response options for “Class Type” to:

- [ ] JK
- [ ] SK
- [ ] JK/SK
- [ ] JK/SK/q
- [ ] SK/1
- [ ] Other

Change “Does this child have Identified Special Needs?” to “Exceptional/Special Needs”

Change “Child’s Language Status to “Child considered EAL/FAL:”

- [ ] Yes
- [ ] No

Change “French Immersion” question to "Language Immersion Program:"
- [ ] French Immersion
- [ ] Other Immersion
- [ ] No

Remove “Other Immersion” question. 

After “Language Immersion Program:” question, add “Aboriginal Status:” questions:

- [ ] Yes
- [ ] No
- [ ] Don’ know

Remove "What is the child's current format of instruction" question.

Add final question “Child has immigrated to Canada within the last two years:”

- [ ] Yes
- [ ] No
- [ ] Don’t Know

**Comment by rennera** [comment]
Completed
