### ISSUE TITLE
2023 PEI – Section E

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#159]
- [x] Qe1. 1. Did this child receive early intervention supports (including but not limited to programs such as Intensive

Behavioural Intervention (IBI), Speech-language pathology, or Occupational Therapy)?

- [x] Prior to, or during pre-kindergarten and now does not   Yes/No/Don't Know
- [x] Beginning in kindergarten     Yes/No/Don't Know
- [x] Both prior to, and during kindergarten      Yes/No/Don't Know
- [x] Specify if known: (open Text)

**Comment by rasope** [comment]
Update question to include "Note"

Qe2. 2. Has this child been in non-parental care on a regular basis prior to kindergarten entry?
Note: “Regular" refers to consistent basis, full or part time, for greater than 6 months.

**Comment by rasope** [comment]
Update response options for qe3.

a. Centre-based, licensed
b. Other Home-based, licensed
c. Home-based, unlicensed, non-relative
d. Relative
e. Other/Don't Know

**Comment by rasope** [comment]
Update qe3. to "3. Attended organized social programs outside of child care such as: sports practices, music
lessons, religion classes or formal language-learning opportunities."

**Comment by rasope** [comment]
Remove Qe4.

**Comment by rennera** [comment]
Complete

**Comment by rennera** [comment]
[2023 PEI Section Epdf.pdf](https://github.com/RADB/Offord-EDI-2020/files/10289960/2023.PEI.Section.Epdf.pdf)
