### ISSUE TITLE
2023 Manitoba – Demographics

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#160]
(All changes are based on current Newfoundland questionnaire)

After “Postal Code” add “Has this child immigrated to Canada within the last two years?”
- [ ] Yes
- [ ] No
- [ ] Don’t know

Update “Class Type” response options to:
- [ ] K
- [ ] K/1
- [ ] Other

Change “Child's language status” to “English/French as Additional Language:”
- [ ] EAL
- [ ] FAL
- [ ] No

Change "French Immersion” question to "Language Immersion Program:"
- [ ] French Immersion
- [ ] Other Immersion
- [ ] No

Remove "Other Immersion:" question

After “Language Immersion Program” question add “Indigenous (First Nations, Metis, or Inuit):”
- [ ] Yes
- [ ] No
- [ ] Don’t know

Remove "What is the child's current format of instruction" questions.

**Comment by rennera** [comment]
Complete
