### ISSUE TITLE
2023 Manitoba - Section E

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#161]
Update response options for “If yes, please specify type of care arrangement (please refer to Guide for examples):” to
- [ ] Centre-based, licensed, non-profit
- [ ] Centre-based, licensed, for profit
- [ ] Other home-based, licensed
- [ ] Other home-based, unlicensed, non-relative
- [ ] Other home-based, unlicensed, relative
- [ ] Child’s home, non-relative
- [ ] Child’s home, relative
- [ ] Other/Don’t/Know

**Comment by rennera** [comment]
Complete
