### ISSUE TITLE
Section E - Remove open text formatting options

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#164]
Can we remove all of the formatting option in open text responses?

![image](https://user-images.githubusercontent.com/24963245/199776099-281825ac-c1a3-4af2-a15f-401f2543ba4a.png)

**Comment by rennera** [comment]
See Issue #156 - the export will strip the HTML on export - but I can also remove the option to allow them to format the text

**Comment by rasope** [comment]
Please remove the option to allow them to format the text.

**Comment by rennera** [comment]
This has been removed.
