### ISSUE TITLE
Teacher Profile Update

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#165]
Hey Andrew. We want to revamp our Teacher Profile questionnaire, and have updated the questionnaire into the 2 sections below. I've also attached a PDF if it's easier for you to work from. 
[2023 Teacher Profile Questionnaire - Nov 4.pdf](https://github.com/RADB/Offord-EDI-2020/files/9955094/2023.Teacher.Profile.Questionnaire.-.Nov.4.pdf)

Adding Section Heading "Teacher Demographics"

1. Do you identify as:

- Male
- Female
- Other

2. Age Category

- 20-29
- 30-39
- 40-49
- 50-59
- 60+

3. Highest level of education
- Teaching certificate, diploma, or license
- Bachelor's degree
- Bachelor of Education degree
- Post-baccalaureate diploma or certificate
- Master's degree
- Doctorate
- Other

3.a. Other - Please Specify: (open text response)
4. How long have you been a teacher? (open text response)
6. How long have you been a teacher of this grade? (open text response)

Add Section Heading "Experience with EDI"

1. Is this your first time completing the EDI?
- Yes
- No

2. How many times have you completed the EDI?
- No previous experience
- 1-2 times
- 3 or more times

3. Have you ever received EDI teacher training?
- Yes
- No

4. If you did receive training, was it helpful?
- Very
- Somewhat
- Not at all

5. Did you find the EDI Guide or Help icons helpful?
- Yes
- No
- Didn't use

6. Did you find the EDI Training Video helpful?
- Yes
- No
- Didn't use/watch

7. Additional comments about EDI training resources, etc.  (open text response)

**Comment by rennera** [comment]
This has been updated and will be rolled out with the larger change.  It has a major database update to go along with the changes.
