### ISSUE TITLE
Ontario - Demographics Section

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#168]
Change “French Immersion” question to "Language Immersion Program:"
- [ ] French Immersion
- [ ] Other Immersion
- [ ] No

Remove "Other Immersion" question

Remove "What is the child's current format of instruction".

Remove "Are you aware whether this child experienced any challenges with online instruction last year? (e.g. from your experience, told to you by parents or another teacher, etc)."

**Comment by rennera** [comment]
Completed
