### ISSUE TITLE
PEI - Section E

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#170]
Qe1 is missing response options. It should look like this

![image](https://user-images.githubusercontent.com/24963245/210598016-aed54466-a1b6-4d6d-86e4-f37b09cafdcf.png)

a. Prior to, or during pre-kindergarten and now does not
b. Beginning in kindergarten 
c. Both prior to, and during kindergarten
Specify if known:  ________________

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/211984639-5b5754cc-5253-45ec-9118-1efd2fa6ed99.png)
