### ISSUE TITLE
PEI - Demographics

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#171]
Update response option (4) in Class Type question from "JK/SK/q" to "o	JK/SK/1"

![image](https://user-images.githubusercontent.com/24963245/210850924-e6ee96e9-8c2e-447e-b917-e708dc23193d.png)

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/211985268-e0df9468-d161-46e4-8df1-38145e1c463f.png)
