### ISSUE TITLE
Manitoba - Demographics

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#172]
Update response options for Student Status question to: 
Student Status: 

- Child in class more than 1 month    
- Child in class less than 1 month
- Moved out of this class
- Moved out of school                
- Other

Sex
Remove "Other" option from Sex question

Move "Communicates adequately in his/her first language" to be the last question in the demographics section.

Update “Class Type” response options to:
- K
- K/1
- Other

Updates response options for "Child Considered EAL/FAL" to 
-EAL
-FAL
-No

Remove Aboriginal question

Add 2 more response options for "Child's First Languages"

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/212011489-c6beafad-7447-4a58-b42c-9f466c9b2d85.png)

![image](https://user-images.githubusercontent.com/3689865/212011521-cbdbc770-dc59-4b2d-a766-0d77c72e1cf0.png)

![image](https://user-images.githubusercontent.com/3689865/212011553-59cf23bf-91f4-4987-a442-4359346525dd.png)

![image](https://user-images.githubusercontent.com/3689865/212011581-31cd4e9d-da2d-482b-a36c-09d5839d1ce8.png)

![image](https://user-images.githubusercontent.com/3689865/212011615-d8ef7831-37ea-490f-a1d9-0ec10b6fca74.png)

![image](https://user-images.githubusercontent.com/3689865/212011659-b47770fe-a24e-4eea-8087-32f6c3bb9f89.png)

Aboriginal Question Removed as well
