### ISSUE TITLE
Ontario - Section E

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#178]
the drop-down menu that occurs twice in Ontario's Section E has some additional/repeating response options. Can you remove the two space indicated in the image below? 

![image](https://user-images.githubusercontent.com/24963245/211054359-9e231684-7948-4c04-9ade-0da8edd641aa.png)

**Comment by rasope** [comment]
Can you remove the "Pre-school / Nursery School" response options from the two drop-down menus?

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/211998062-6d8530d3-5711-4a40-8f50-a2cf2a40630f.png)

Option also removed.
