### ISSUE TITLE
Gender Pre-fill

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#179]
Gender that is uploaded seems to be prefilling on the class list, but not on the questionnaire. Can gender pre-fill on the questionnaire?

**Comment by rennera** [comment]
This has been corrected - it was loading correctly but the values needed to be aligned with this years value.
`--male
  UPDATE [EDI.Service].[LUData].[LookupSetOptions] SET Value =6 WHERE yearid=3 and id in( 665,862,963)
  --female
  UPDATE [EDI.Service].[LUData].[LookupSetOptions] SET Value =7 WHERE yearid=3 and  id in( 664,863,964)
  --other
  UPDATE [EDI.Service].[LUData].[LookupSetOptions] SET Value =8 WHERE yearid=3 and  id in( 861,962)`
