### ISSUE TITLE
Manitoba - Demographics

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#185]
Remove "Indigenous (First Nations, Metis, or Inuit)" question

**Comment by rasope** [comment]
Update French response options for "Programme d’immersion linguistique" to

- Immersion française
- Autre langue d’immersion
- Non (aucune immersion)

**Comment by rasope** [comment]
Hey Andrew. Can you get this done tonight? MB starts collecting on Monday.

**Comment by rennera** [comment]
These are both updated.
![image](https://user-images.githubusercontent.com/3689865/218009605-5b5975b9-e5f5-441d-a2f1-c707ef23fde0.png)
