### ISSUE TITLE
Gender for newly added students

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#187]
When adding new students to the class list, can we limit the gender responses to one Male option and and 1 Female option? There shouldn't be an "other" option. Also, gender selected here for newly added students is appearing on the class list but not pre-filling to the questionnaire. 

![image](https://user-images.githubusercontent.com/24963245/214097837-c46f3d04-4f22-4ded-8f93-d06a6ea1747b.png)

**Comment by rennera** [comment]
This has been updated:
![image](https://user-images.githubusercontent.com/3689865/216881860-bede902d-cb5f-411c-bfd7-3d30f916e32c.png)
