### ISSUE TITLE
Remove News Feed from Teacher Dashboard

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#188]
![image](https://user-images.githubusercontent.com/24963245/214098875-f7b2c870-079c-4121-b52d-b55db3e23bf6.png)

**Comment by rennera** [comment]
This has been removed from the teacher dashboard.
![image](https://user-images.githubusercontent.com/3689865/216883681-903bcb3a-b82a-4966-af08-7b65bd4965cd.png)
