### ISSUE TITLE
How do I update/change a teacher login?

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#189]
In the event that we need a differ email/login associated with an existing class, how do I update this information?

**Comment by rennera** [comment]
Is this a replacement teacher or an additional teacher?

**Comment by rasope** [comment]
Replacement teacher. I just couldn’t figure out how to do it on the system. I tested a ew different ways that didn’t work. 


--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University 
(905) 525-9140 ext. ***@***.***
edi.offordcentre.com




On Jan 24, 2023, at 4:06 PM, rennera ***@***.***> wrote:




﻿

Is this a replacement teacher or an additional teacher?
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>
