### ISSUE TITLE
Add Provinces for Resources

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#190]
Can you add Manitoba and PEI folders to the resource page?

![image](https://user-images.githubusercontent.com/24963245/214103844-f6ed8869-3e5a-46dc-897c-0f563016257a.png)

**Comment by rennera** [comment]
The system will automatically create the folders when a teacher from that province logs in and got to the resource page in the teacher portal.  I logged in as the mock accounts and it created the folders.
![image](https://user-images.githubusercontent.com/3689865/214414223-b55e7edc-25fc-45e9-b29d-532fc35f48a9.png)
