### ISSUE TITLE
Add PR to webmaster email

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#191]
I don't think I've been added back after my mat leave. Can you make sure the [webmaster@e-edi.ca](mailto:webmaster@e-edi.ca) emails are coming my way? rasope@mcmaster.ca

**Comment by rasope** [comment]
A tested the email and got the bounce back below
![image](https://user-images.githubusercontent.com/24963245/214396470-c220afea-f730-443b-a11b-71157212c71c.png)

**Comment by rennera** [comment]
This is the updated list of recipients - please let me know if anyone needs to be removed.
![image](https://user-images.githubusercontent.com/3689865/214398036-3943485f-40da-4667-8558-0a1e71239435.png)

I have updated the server settings to correct the error above as well.

**Comment by rasope** [comment]
Thanks! You can remove Caroline Reid-Westoby.

**Comment by rennera** [comment]
Done!
![image](https://user-images.githubusercontent.com/3689865/214398561-ed8dc995-9943-4c10-a35f-b2665bc73c71.png)

**Comment by rennera** [comment]
Test email sent could you confirm receipt

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/214399367-931a1e04-9379-4d54-9d1c-4991ca6a411c.png)

**Comment by rasope** [comment]
Received 👍

--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University
(905) 525-9140 ext. 27051<tel:(905)%20525-9140;27051>  |  ***@***.******@***.***>
edi.offordcentre.com
