### ISSUE TITLE
Section E - Manitoba

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#192]
Remove the < p > formatting from these four response options in Section E? I can't seem to edit it out from the admin side. Can you look at the French side too? When I toggle this section to French there is a lot more of the code appearing. 

The response options should read:

- Centre-based, licensed, non-profit
- Centre-based, licensed, for profit
- Other home-based, licensed
- Other home-based, unlicensed, non-relative
- Other home-based, unlicensed, relative
- Child's home, non-relative
- Child's home, relative
- Other/Don't Know
- 
Please delete the last response option.

![image](https://user-images.githubusercontent.com/24963245/214325512-9c6f0764-b08b-49c5-a6a4-d9b71cd4de77.png)

**Comment by rasope** [comment]
Remove final question "If you answered 'yes' to Indigenous status (page 1) please elaborate (check all that apply)"

**Comment by rasope** [comment]
This one too. Can you get this done tonight? MB starts collecting on Monday.

**Comment by rennera** [comment]
These have been updated and variables aligned with question as shown:
![image](https://user-images.githubusercontent.com/3689865/218014750-063985e7-8cd1-40ee-8e9c-cbabb19950d5.png)
