### ISSUE TITLE
Teacher Resources - all provinces

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#199]
After deploying the new update, teachers can see the name of the teacher resources. And they are unable to open them.

![image](https://user-images.githubusercontent.com/24963245/216655521-82552b37-d952-482d-a4b1-60f2f3de43ec.png)

**Comment by rennera** [comment]
Hey Dylan - this class in the CSS is causing the filenames in the grid to disappear.
![image](https://user-images.githubusercontent.com/3689865/216883033-e5f82ba6-c044-4adf-9edc-f62d5e8f2fc9.png)
![image](https://user-images.githubusercontent.com/3689865/216883063-92bd8386-2dd6-4c2b-9d67-781f665e5cad.png)

I am not sure where else this is being used but disabling these two items puts the filenames visible again in the grid.
![image](https://user-images.githubusercontent.com/3689865/216883195-de38f648-a43b-44e8-a5a7-9ee2430523e5.png)
![image](https://user-images.githubusercontent.com/3689865/216883219-d5bd7751-bb07-4a12-b1d0-a493b638614d.png)

**Comment by rennera** [comment]
This has been corrected.
