### ISSUE TITLE
Help & Configure abilities lost

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#201]
Help Buttons
- The Help icon is not appearing for a lot of the questions in the demographics section. It looks like they might be piled on top of each other beside the first question each of "block". Can you get the Help icon to appear beside each question in the demographics section?
![image](https://user-images.githubusercontent.com/24963245/216674251-0a311165-cf43-4605-b842-63bd81d54e98.png)

Configure button
- Previously on the admin side of the system I had access to a "Configure button" that was beside the "Help" button beside each questions. The code that is blending in the "Help" button is also making my "Configure" button disappear. Can you edit this so it only impacts the "help" button and not the "configure" button?

![image](https://user-images.githubusercontent.com/24963245/216673525-13432486-e843-46bb-8fc7-61908e2c4d94.png)

**Comment by rasope** [comment]
Hey Andrew, were you able to deploy their code update?

**Comment by rennera** [comment]
Deployed tonight
