### ISSUE TITLE
PEI - Demographics

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#202]
Update French response options for "Situation de l’élève:" (Class Type)

- pré-maternelle 
- maternelle
- pré-maternelle/maternelle
- pré-maternelle/maternelle/1
- Autre

**Comment by rennera** [comment]
Hey Patricia - The english values for this question are as follows:
![image](https://user-images.githubusercontent.com/3689865/217435963-e49a14d0-95fb-435f-8767-541396d35686.png)

**Comment by rennera** [comment]
I have updated to this - let me know if it is not correct:
![image](https://user-images.githubusercontent.com/3689865/217440255-455f7807-77e5-4d74-94a8-bbf424954985.png)
