### ISSUE TITLE
PEI - weird issue with Section E

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#203]
Hey Andrew,

I've heard from about 5 teachers today in PEI who have all run into the same issue. They cannot complete, save, or Lock in Section E for 1 questionnaire in their classes. This only happens for 1 child in their class and they can complete the rest of the questionnaires without any problems.  Some of the EDI ID numbers it's happening to are below. Any insight? 

231160102302412
231160200101406
231160101302408

**Comment by rennera** [comment]
This has been corrected and tested.  It was an issue with a variablename in the checkboxes.

`UPDATE [EDI.Service].[EDI].[Questionnaires.Configuration] SET variablename = 'HomeUnlicensedNonRelative', EntityField= 'HomeUnlicensedNonRelative' WHERE ID =1911`
