### ISSUE TITLE
MB - Section E

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#207]
Remove final question from Section E "<html>
<body>

If you answered 'yes' to Indigenous status (page 1) please elaborate (check all that apply) | Yes | No | Don't Know
-- | -- | -- | --
  | First Nations | Yes | No | Don't Know
  | Inuit | Yes | No | Don't Know
  | Metis | Yes | No | Don't Know
  | Other

</body>
</html>"

**Comment by rennera** [comment]
Question removed.
