### ISSUE TITLE
Multiple accounts for teachers

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#209]
Hey Andrew. This is an issue for us to think about.

I'm running into issues for Manitoba where teachers who teach two classes, have different teacher names (database issues on their end), and the same email address. In these situations, teachers can only log in with 1 of their accounts and the other doesn't work. For the account that does work, their dashboard shows 0 students, but the class list does include their students. These teachers have no way of accessing their remaining students.

![image](https://user-images.githubusercontent.com/24963245/218544685-37c9a497-16d7-440e-9ea1-d253ed411cb9.png)
![image](https://user-images.githubusercontent.com/24963245/218544734-856c4b02-fa3f-4a73-9356-08cc55944aa6.png)

In these cases the email address are the same, but the teacher name is slightly different. Previously as long as the email address was the same the system would pull up both classes. Is there a way to link them? I can't seem to update and save any changes to teacher name on the system.

**Comment by rennera** [comment]
I will have a look at this.

**Comment by rasope** [comment]
Okay. And if the email address and teacher name are exactly the same, they do get combined (only the first pw works). The issue arises when the email or the name are different, and I have no way of updating any info to make it link.

**Comment by rennera** [comment]
I created a list of duplicate teacher emails and I can see they link back to the same userid which is good.  
`SELECT * FROM edi.Teachers WHERE email in (SELECT email 
  FROM [EDI.Service].[EDI].[Teachers]
  where yearid =3
  group by email 
  having count(1)>1)
order by email`

**Comment by rasope** [comment]
Ok here is an example: 

MELISSA SIGVALDASON	me
[classlist.SIGVALDASON.2023.xlsx](https://github.com/RADB/Offord-EDI-2020/files/10725496/classlist.SIGVALDASON.2023.xlsx)
lissa.sigvaldason@7oaks.org	08801502
MELISSA SIGVALDSON	melissa.sigvaldason@7oaks.org	08801503

This teacher has the same email address but slightly different teacher name. This is a spelling error because our partner in Manitoba were sloppy with their database. 08801503 works and 08801502 doesn't.

**Comment by rennera** [comment]
The duplicates were removed and Patricia recreated the records correctly.
