### ISSUE TITLE
Add class to body if admin

### ISSUE THREAD

**Issue by ddemoe-md** [RADB/Offord-EDI-2020#211]
Hello Andrew,

I imagine you could do this much quicker than I can.. and if this is a big ask let me know and we'll pivot.

Would it be possible to add a class to the HTML body tag if the logged in user is an admin?

`<body class="admin">`

Thanks!

**Comment by rennera** [comment]
Hey Dylan,

 

Let me have a quick look at this.   

 

 

 

From: ddemoe-md ***@***.*** 
Sent: Friday, February 17, 2023 12:50 PM
To: RADB/Offord-EDI-2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RADB/Offord-EDI-2020] Add class to body if admin (Issue #211)

 

Hello Andrew,

I imagine you could do this much quicker than I can.. and if this is a big ask let me know and we'll pivot.

Would it be possible to add a class to the HTML body tag if the logged in user is an admin?

<body class="admin">

Thanks!

**Comment by rennera** [comment]
Hey Dylan I have added this to the admin section and checked in the code.
