### ISSUE TITLE
Site Summary for entire Province

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#212]
Hey Andrew. Manitoba is requesting a site summary for the entire province. Is there a way I can generate this? I can generate a report for individual sites using "GetChildrenBySite", but was wondering if there was a way I could pull the Locked/Progress data for the whole province. 

I'm trying to generate a "GetChildrenDatabyProvince" report, but it doesn't appear to be working. 
![image](https://user-images.githubusercontent.com/24963245/220731208-708e887b-fb58-4730-9934-8775421221cd.png)

**Comment by rennera** [comment]
Ah yes – I haven’t added Manitoba to the report.  Let me see what I can do.

 

From: rasope ***@***.*** 
Sent: Wednesday, February 22, 2023 1:59 PM
To: RADB/Offord-EDI-2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RADB/Offord-EDI-2020] Site Summary for entire Province (Issue #212)

 

Hey Andrew. Manitoba is requesting a site summary for the entire province. Is there a way I can generate this? I can generate a report for individual sites using "GetChildrenBySite", but was wondering if there was a way I could pull the Locked/Progress data for the whole province.

I'm trying to generate a "GetChildrenDatabyProvince" report, but it doesn't appear to be working.
 <https://user-images.githubusercontent.com/24963245/220731208-708e887b-fb58-4730-9934-8775421221cd.png>

**Comment by rennera** [comment]
That report has been updated to include Manitoba.

 

From: rasope ***@***.*** 
Sent: Wednesday, February 22, 2023 1:59 PM
To: RADB/Offord-EDI-2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RADB/Offord-EDI-2020] Site Summary for entire Province (Issue #212)

 

Hey Andrew. Manitoba is requesting a site summary for the entire province. Is there a way I can generate this? I can generate a report for individual sites using "GetChildrenBySite", but was wondering if there was a way I could pull the Locked/Progress data for the whole province.

I'm trying to generate a "GetChildrenDatabyProvince" report, but it doesn't appear to be working.
 <https://user-images.githubusercontent.com/24963245/220731208-708e887b-fb58-4730-9934-8775421221cd.png>

**Comment by rasope** [comment]
Awesome! Thank you. It's been almost 23 mins and the wheel is still spinning. I'm sure its a large file so I'll keep waiting.

**Comment by rennera** [comment]
There is a duplicate variablename – I am looking at it now.

**Comment by rennera** [comment]
Refresh the page and run it now it should be good!
