### ISSUE TITLE
Section E - check for completion MB, NL, PEI, 

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#214]
This question needs to be removed from the check for completion similar to the preceding question. It's not required that teachers complete this question

![image](https://user-images.githubusercontent.com/24963245/221290938-68c84d14-154e-47c8-8e69-5c43d752769d.png)

**Comment by rasope** [comment]
This continues to be an issue for a lot of teachers. They leave this questions blank, but the section shows as incomplete.

**Comment by rennera** [comment]
The required fields on Section E have all been reviewed and updated.
![image](https://user-images.githubusercontent.com/3689865/223318366-94a08d6b-c405-4fdc-837e-5d8445d2c49d.png)
