### ISSUE TITLE
Data reports

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#215]
Can you set-up the system to generate data reports by province for Nova Scotia & Newfoundland?

Also, I'm running into issues producing reports for some sites (not all) that were working a few weeks ago. I'm trying 245, 246, and 247 and am getting the spinning wheel. 

![image](https://user-images.githubusercontent.com/24963245/223211794-ec21ba68-b8a3-40c6-b9eb-f1e6552dbc07.png)

**Comment by rennera** [comment]
NOVA SCOTIA and NFLD are already included in the report.

We only need to worry about newly added provinces that were not previously in the report.

**Comment by rennera** [comment]
There was a carriage return after a variable name that was adjusted which caused an illegal HTML value in the query &#x0D;

This has been removed and it corrected the other reports.

**Comment by rennera** [comment]
I added a line of code to deal with it if it happens again.
`-- remove any carriage returns from the variablenames
	SET @Columns = replace(@columns,'&#x0D;','')`
