### ISSUE TITLE
Unable to Add Student - NS

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#217]
I have a Nova Scotia teacher who is unable to add a student to their class list. They can click +Add from the class list, but after entering the student's info and saving, nothing appears on their class list. I tried myself and it's not working.

Her acct is RobersS@ccrce.ca and pw 07201504

**Comment by rennera** [comment]
Needed to add the year filter to the teacher - errors occurred when teacher had conducted EDI in previous years.
`var teacher = dbContext.Teachers.Where(t => t.UserId == UserSettings.UserID && t.YearId == UserSettings.YearId).FirstOrDefault();`
