### ISSUE TITLE
Trouble adding a student

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#218]
A teacher in Newfoundland [kimberleypoole@nlesd.ca](mailto:kimberleypoole@nlesd.ca) can't add a student to her list. It's the same issue we were running into last week. The coordinator said this is happening to multiple teachers.

**Comment by rennera** [comment]
Sorry I didn’t deploy the change last week - I will deploy it tonight!On Mar 13, 2023, at 12:46 PM, rasope ***@***.***> wrote:﻿
A teacher in Newfoundland ***@***.*** can't add a student to her list. It's the same issue we were running into last week. The coordinator said this is happening to multiple teachers.

**Comment by rennera** [comment]
I went through the children that failed to add
There are 4 duplicates that I will remove
These 4 teachers - had duplicates - same local id and DOB
sophiahewitt@nlesd.ca
pamelamcdonald@nlesd.ca
angelanurse@nlesd.ca
shelleywhitehorne@nlesd.ca
There were 10 other teachers that tried to add a student and it was misaligned. 7 tried to add yesterday
Dana.Grimes@yk1.nt.ca
kimberlypoole@nlesd.ca
shelleywhitehorne@nlesd.ca
rosesmith@nlesd.ca
lornadwyer@nlesd.ca
peggyfennemore@nlesd.ca
angelanurse@nlesd.ca
cathytulk@nlesd.ca
pamelamcdonald@nlesd.ca
sophiahewitt@nlesd.ca
I am moving those additions to their classes
I will double check to see if they added today

**Comment by rennera** [comment]
`DELETE FROM EDI.Teachers WHERE ID = 71380
DELETE FROM EDI.Teachers WHERE ID = 71360
DELETE FROM EDI.Teachers WHERE ID = 71389
DELETE FROM EDI.Teachers WHERE ID = 66651
UPDATE EDI.Children SET teacherid = 2020 WHERE id =71349 AND teacherID = 1304
UPDATE EDI.Children SET teacherid = 5182 WHERE id =71364 AND teacherID = 1375
UPDATE EDI.Children SET teacherid = 5193 WHERE id =71375 AND teacherID = 1530
UPDATE EDI.Children SET teacherid = 5222 WHERE id =71359 AND teacherID = 1530
UPDATE EDI.Children SET teacherid = 5298 WHERE id =71340 AND teacherID = 1413
UPDATE EDI.Children SET teacherid = 5312 WHERE id =71381 AND teacherID = 1467
UPDATE EDI.Children SET teacherid = 5320 WHERE id =71384 AND teacherID = 1338
UPDATE EDI.Children SET teacherid = 5349 WHERE id =71363 AND teacherID = 1338
UPDATE EDI.Children SET teacherid = 5377 WHERE id =71121 AND teacherID = 1256
UPDATE EDI.Children SET teacherid = 5407 WHERE id =71120 AND teacherID = 1256
`

**Comment by rennera** [comment]
Everything is realigned correctly.
