### ISSUE TITLE
Alberta Questionnaire - Demographics

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#219]
Hey Andrew. I'm going to add the updates for Alberta customizations based off the Newfoundland questionnaire. 
[AB Demos.pdf](https://github.com/RADB/Offord-EDI-2020/files/10982939/AB.Demos.pdf)

- [x] - Add "Registered Non-attender" option to **Student Status** question

- [x] - Change **Class Assignment** response option to "K4"

- [x] - Remove **Class Type** question

- [x] - Add **Band Membership** question. Add response below:
Ermineskin Cree Nation
Louis Bull Tribe
Montana First Nation
Samson Cree Nation
Samson Cree Nation
Other 
Specify:________________________

- [x] - Change **Does this child have Identified Exceptionalities** to **Identified special needs (Excluding speech):**

- [x] - Remove **Child's Language Status** question
- [x] -  Remove **Language Immersion Program** question
- [x] - Remove **Aboriginal Status** question

- [x] - Change **Child's First Language** to **Child's Language(s):** Update response fields to below:
English
Cree
Other (Drop down)

- [x] - Remove **Child has immigrated to Canada within the last 2 years:** question

**Comment by rasope** [comment]
Teachers are being released this week to collect. Can we prioritize getting this up?

**Comment by rennera** [comment]
I have these changes made but I need to test it before deploying.  I will take my laptop and test on the plane so I can deploy when we get there later today.

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/230333330-9df969c1-b174-4d07-b9f9-c0938602dd8c.png)

**Comment by rasope** [comment]
[upload.MESC.2023.xlsx](https://github.com/RADB/Offord-EDI-2020/files/11170085/upload.MESC.2023.xlsx)

 Here is the upload data for the Alberta group if you want it.

**Comment by rennera** [comment]
Thanks I hadn’t seen this when I asked today.On Apr 6, 2023, at 7:33 AM, rasope ***@***.***> wrote:﻿
upload.MESC.2023.xlsx
Here is the upload data for the Alberta group if you want it.
