### ISSUE TITLE
Icon for the site needs to be updated.

### ISSUE THREAD

**Issue by rennera** [RADB/Offord-EDI-2020#22]
Change from this 
![image](https://user-images.githubusercontent.com/3689865/103857180-fbc71c00-5083-11eb-8742-469e2189a929.png)

to EDI logo if we can make it fit.

**Comment by blazornut** [comment]
done, change favicon

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/104860003-2a9c8800-58f7-11eb-9438-4d552befd879.png)
