### ISSUE TITLE
Alberta Questionnaire - Section E

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#220]
The entire section needs to be updated. 
[AB Section E.pdf](https://github.com/RADB/Offord-EDI-2020/files/10982998/AB.Section.E.pdf)

**To the best of your knowledge, please mark all that apply to this child:**
Attended Head Start    Yes/no/Don't Know

Attended an early intervention program (such as Early Years)     Yes/no/Don't Know
Specify if known: _____________________________

Attended other community programs or activities (e.g. round dances, pow wows, drumming, sports, summer camps etc.)        Yes/no/Don't Know    
Specify if known: _____________________________

Is there a fluent Cree speaker in the home?       Yes/no/Don't Know

**What was the main type of Monday to Friday childcare arrangement for this child before K4 entry?**
- Child's home with parent /guardian
- Home-based, unlicensed care (e.g. relative or friend other than primary caregivers) 
- Centre-based, licensed, daycare
- Licensed daycare in someone’s home (e.g. dayhome)
- Home-based, paid, unlicensed care (e.g. babysitter)
- Other/don't know

**Comment by rasope** [comment]
Hey Andrew. This Alberta group is planning to begin collection next week, and I can't upload the data until the province is ready. Is it possible to get this up and running for next week?

**Comment by rennera** [comment]
Do we need the comments at the end of this section?

**Comment by rasope** [comment]
Nope


--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University 
(905) 525-9140 ext. ***@***.***
edi.offordcentre.com




On Apr 5, 2023, at 10:34 PM, rennera ***@***.***> wrote:




﻿

Do we need the comments at the end of this section?
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by rennera** [comment]
I was just going to say I see it in the pdf at the top.... Confirmed we do NOT need comments!
