### ISSUE TITLE
Admin search bar on class list page

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#224]
The aesthetic changes from Media Doc have carried over to the class list page on the admin side, and I can no longer see my search bar to look up questionnaires by EDI ID. Can I get this back?

![image](https://user-images.githubusercontent.com/24963245/226635427-ff3340e1-fe6f-4762-845b-e65a50b24747.png)

**Comment by rennera** [comment]
I will assign this to Dylan.On Mar 21, 2023, at 10:21 AM, rasope ***@***.***> wrote:﻿
The aesthetic changes from Media Doc have carried over to the class list page on the admin side, and I can no longer see my search bar to look up questionnaires by EDI ID. Can I get this back?

**Comment by ddemoe-md** [comment]
@rennera 
Committed CSS to fix this. However, is it possible to add the `admin` class to the dashboard area (for admin users)? You've done this for the questionnaire already.. but can we also add to the dashboard?

**Comment by rennera** [comment]
Let me look at this and see what I can do!

**Comment by rennera** [comment]
Done 
![image](https://user-images.githubusercontent.com/3689865/230250555-745ea62b-98c0-420c-a554-c84944480407.png)
