### ISSUE TITLE
"Confirm Lock" text off screen

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#225]
Can this be fixed? 

![image](https://user-images.githubusercontent.com/24963245/226950588-44717646-0406-4cb9-8f41-997d694e8372.png)
![image](https://user-images.githubusercontent.com/24963245/226950866-fc87818d-1d22-4b6a-b6ab-cc419c9e3c56.png)

**Comment by rennera** [comment]
This is likely a Dylan CSS change – but I will have a look to see if I can correct it easily.

 

From: rasope ***@***.*** 
Sent: Wednesday, March 22, 2023 11:20 AM
To: RADB/Offord-EDI-2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RADB/Offord-EDI-2020] "Confirm Lock" text off screen (Issue #225)

 

Can this be fixed?

 <https://user-images.githubusercontent.com/24963245/226950588-44717646-0406-4cb9-8f41-997d694e8372.png> 
 <https://user-images.githubusercontent.com/24963245/226950866-fc87818d-1d22-4b6a-b6ab-cc419c9e3c56.png>

**Comment by ddemoe-md** [comment]
@rennera98 
I've just committed a fix for this.

**Comment by rennera** [comment]
Thanks Dylan – I will get this released asap.
