### ISSUE TITLE
Remove "Edit" button from class list page 

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#226]
This only happens when the class list is viewed in French, not English.

![image](https://user-images.githubusercontent.com/24963245/226952460-c2833395-4f6d-4c4e-afd9-3e11fad9099d.png)

**Comment by rennera** [comment]
Hey Dylan here is the English view...
![image](https://user-images.githubusercontent.com/3689865/230243751-c69289da-3e10-45b9-b3c7-0e803212b608.png)

**Comment by rennera** [comment]
I added this to your css `#GridChild_Éditer`
![image](https://user-images.githubusercontent.com/3689865/230249000-6c2b84c6-c470-4a4e-bcd8-509484b60022.png)


![image](https://user-images.githubusercontent.com/3689865/230248934-b54689da-cf50-44f0-a966-88b408284ef8.png)
