### ISSUE TITLE
Child's date of birth isn't saving - Ontario

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#229]
For Ontario...

When the teacher updates/changes the child's DOB in the questionnaire, it does not save after clicking Save or moving to the next section. It also doesn't update on the class list page.

**Comment by rasope** [comment]
Hey Andrew, 
Do you think you'll have time this weekend to fix these Ontario issues too? I have school boards that want to complete next week in Ontario :| Thanks!

**Comment by rennera** [comment]
This is odd - if i change the text of DOB typing it saves correctly - selecting from the calendar does not.  Investigating

**Comment by rennera** [comment]
I added an event handler that needed to be in place with an upgrade to this control and it is not functioning correctly.
![image](https://user-images.githubusercontent.com/3689865/230243135-0044a297-1140-4315-ac23-77901b4eb9d7.png)

Updating the date on the page and the class list.
