### ISSUE TITLE
Child's First Language - Ontario

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#230]
Can we remove the first (blank) response option from the check for completion? This questionnaire is indicated as being complete when it hasn't been answered yet. 

![image](https://user-images.githubusercontent.com/24963245/228042128-6b25c796-3bb3-47c4-b938-c0c1d5987cc2.png)

**Comment by rennera** [comment]
I have corrected the validation 
![image](https://user-images.githubusercontent.com/3689865/230231808-01513987-fa0d-47ae-9ac3-58c004afed81.png)
