### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#231]
I've been uploading things all week for Ontario, and the system has been awesome! But of course, I'm running into an error with this very small template of 37 kids. I don't see a glaring issue in the content. Wondering if you can identify the root of the error.

[upload.PPSSB.ON.2023.xlsx](https://github.com/RADB/Offord-EDI-2020/files/11115057/upload.PPSSB.ON.2023.xlsx)

![image](https://user-images.githubusercontent.com/24963245/228936961-a740e2f8-f8f5-43b1-8b3e-8ed5aa6b4ba3.png)

**Comment by rennera** [comment]
I’ll checkOn Mar 30, 2023, at 2:59 PM, rasope ***@***.***> wrote:﻿
I've been uploading things all week for Ontario, and the system has been awesome! But of course, I'm running into an error with this very small template of 37 kids. I don't see a glaring issue in the content. Wondering if you can identify the root of the error.
upload.PPSSB.ON.2023.xlsx

**Comment by rasope** [comment]
Oh I’m so sorry Andrew. If that’s the air I’ll update it and fix the file! So sorry about that


--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University 
(905) 525-9140 ext. ***@***.***
edi.offordcentre.com




On Mar 31, 2023, at 9:40 AM, rennera ***@***.***> wrote:




﻿

Looks like the DOB's all have the wrong years. I will confirm
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by rennera** [comment]
no problem at all!

It is the first entry 2107-06-09

**Comment by rennera** [comment]
The Date fields have a valid range...
![image](https://user-images.githubusercontent.com/3689865/229177530-969742b6-5f30-4c6b-9e53-d854209b804c.png)

**Comment by rennera** [comment]
I added a more acceptable error message for this scenario.
![image](https://user-images.githubusercontent.com/3689865/229185775-d8206108-14cf-46f6-90b6-b6dea750df1b.png)
