### ISSUE TITLE
Teacher Login Issues

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#232]
Hey Andrew. I'm using site 330 for a research study. It has about 90 teachers. None of the teachers are able to log in right now. None of the credentials for that site are working. Things uploaded properly so I don't know what the issue is. See attached file. for logins and passwords. 

[classlist.ETS.2023.xlsx](https://github.com/RADB/Offord-EDI-2020/files/11122160/classlist.ETS.2023.xlsx)

**Comment by rasope** [comment]
Teachers are trying to complete again today still don't have access.

**Comment by rasope** [comment]
Hmm I know why this is happening. This teacher's email address is also uploaded for their schoolboard collection, so they can't access their questionnaire for the research study. We are going to continue to run into this issue. I'm going to try and think of a way I can work around this, but we need a solution. This is going to happen for at least 100 teachers in Ontario

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/229580999-d0cacefe-04dd-482d-adc0-e57082836fbd.png)

The second teacher needed to be removed.  The dashboard reports on the last teacher with the same ID.  Once I removed the duplicate teacher the problem was resolved.
