### ISSUE TITLE
Alberta?

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#235]
I'm sorry to bother you on vacation. I can't upload the file for our Alberta group. I'm getting the error below when I try to process. The upload file is attached here again. Maybe I'm doing something wrong in the upload. Teachers are being released to collect this data!

![image](https://user-images.githubusercontent.com/24963245/230980351-bc0c73be-ba05-4cbe-b6fa-5f66fe3a6c73.png)

[upload.MESC.2023.xlsx](https://github.com/RADB/Offord-EDI-2020/files/11193343/upload.MESC.2023.xlsx)

**Comment by rennera** [comment]
This was corrected and released earlier this week.
