### ISSUE TITLE
Admin Navigation issues

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#242]
Hmm. Something has changed in the admin side when I try to navigate- If I select a site, it lists all of the school on the system (not just the schools in that site). If I select a school, it lists all teachers in the whole system (not just the teachers in the school).

See Below. Site 851 only has only school within it. But the system is listing all 4,000+ schools. 

![image](https://github.com/RADB/Offord-EDI-2020/assets/24963245/55db8564-22bd-4e05-a110-2290ea0b273b)

**Comment by rennera** [comment]
oh i will correct this...

**Comment by rennera** [comment]
I have corrected this issue and it will be released with the next release

**Comment by rennera** [comment]
Schools at a site
![image](https://github.com/RADB/Offord-EDI-2020/assets/3689865/0466f4c5-7f8b-4dcd-99f8-3dad3f8dfcc8)

Teachers at a school
![image](https://github.com/RADB/Offord-EDI-2020/assets/3689865/72a3275e-b98c-44fe-9471-f441a85c6e55)

All very fast now
