### ISSUE TITLE
Error message in upload

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#243]
Hey Andrew. Can you elaborate on this error message? I don't know what the issue is, but the passwords don't work. 
![image](https://github.com/RADB/Offord-EDI-2020/assets/24963245/6524fb9f-3a05-4034-957f-0602a7f96176)

**Comment by rennera** [comment]
Thanks Patricia – I will deal with this right now

**Comment by rennera** [comment]
50Gb of data has been added to the system to deal with the rapid consumption of logs generated by the Ontario data collection.
![image](https://github.com/RADB/Offord-EDI-2020/assets/3689865/5be43fdd-e5d2-4b19-b698-b96d620ffd52)
Expanded to 250Gb 
![image](https://github.com/RADB/Offord-EDI-2020/assets/3689865/55ff840c-2e15-44bb-866e-376495920b98)
