### ISSUE TITLE
New site* First Nations Collection

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#244]
Hi Andrew, 

We have a new site collecting. They will use a clone of the Ontario questionnaire but with 1 additional question. Can you add the question below to the end of the Demographics section? 

They will need a new site code. Can we use 15? We are going to make site 15 a First Nations Specific site moving forward. 

Does this child have familiarity with Anishinaabemowin/Nishnaabemowin/Lenape (or Indigenous) Language: 
- Yes  
- No   
- Don’t know

**Comment by rasope** [comment]
Hey Andrew. This site is waiting to collect! Can we move on this?

**Comment by rennera** [comment]
Shoot I didn’t see this til now.  I will get to it ASAP On Jun 13, 2023, at 8:55 AM, rasope ***@***.***> wrote:﻿
Hey Andrew. This site is waiting to collect! Can we move on this?

**Comment by rennera** [comment]
Do you have a help guide for this group?  Or should I use the Ontario guide?

**Comment by rasope** [comment]
[2023 KEB EDI Guide.pdf](https://github.com/RADB/Offord-EDI-2020/files/11747517/2023.KEB.EDI.Guide.pdf)
 
I do! Thanks so much. Can i upload to site 15?

**Comment by rennera** [comment]
Idea being teachers won't need multiple emails

**Comment by rennera** [comment]
FirstNations Added to Questionnaires
![image](https://github.com/RADB/Offord-EDI-2020/assets/3689865/893a8eb1-e3b9-473e-a1dd-6531e60e7b0f)

Added the EDICODE to the provinces table
![image](https://github.com/RADB/Offord-EDI-2020/assets/3689865/73891e7a-0b2b-46cd-be56-bc21b010d26a)

Added FirstNations to the questionnaires
![image](https://github.com/RADB/Offord-EDI-2020/assets/3689865/f9b665d7-61ca-47f0-baa9-f09fc3cbdeb4)
