### ISSUE TITLE
First Nations Questionnaire

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#250]
Hi Andrew. We want to update our provide code "15" for our First Nations collection. We have developed a First Nations questionnaire that all of our FN partners will use. The only customizations we will allow are to add response options to certain questions. This will prevent us from having to create a new province code each time we have a slightly different questionnaire. 

This questionnaire is based off of our current province 15 questionnaire. We have only made modifications to the Demographics page and to Section E. See Attached. 

For the "Spoken Languages" question, can we move certain response options to the top of the drop down list? We would like the list to begin with 
- English
- Cree
- Algonquian languages
- Ojibway
- Oji‑Cree
- Dene
followed by typical drop down list

The updated Demographics Section & Section E are attached. Is it easier for me to list things for you individually in Github, and create a new issue for each section? Let me know! 

[FN Questionnaire for Andrew Renner.pdf](https://github.com/RADB/Offord-EDI-2020/files/13548725/FN.Questionnaire.for.Andrew.Renner.pdf)

**Comment by rennera** [comment]
These changes have been deployed to production.
