### ISSUE TITLE
FN questionnaire - Demographics

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#251]
Hey Andrew. Can we update this question to read "Child's Spoken Languages":

![image](https://github.com/RADB/Offord-EDI-2020/assets/24963245/d115903b-b513-47f1-9462-439cc159bf0e)

**Comment by rennera** [comment]
Yes of course – I will do that right away!

 

From: rasope ***@***.*** 
Sent: Wednesday, February 14, 2024 9:41 AM
To: RADB/Offord-EDI-2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RADB/Offord-EDI-2020] FN questionnaire - Demographics (Issue #251)

 

Hey Andrew. Can we update this question to read "Child's Spoken Languages":

image.png (view on web) <https://github.com/RADB/Offord-EDI-2020/assets/24963245/d115903b-b513-47f1-9462-439cc159bf0e>

**Comment by rennera** [comment]
This has been changed for the FirstNations questionnaire.
