### ISSUE TITLE
Document Manager - Teacher View

### ISSUE THREAD

**Issue by rennera** [RADB/Offord-EDI-2020#46]
Disable the ability to create new folders and upload.
![image](https://user-images.githubusercontent.com/3689865/104477255-e162d600-558e-11eb-98c1-7c7becdb20cf.png)

When files are present - only allow download.
![image](https://user-images.githubusercontent.com/3689865/104477352-ff303b00-558e-11eb-97ec-8b5fc5e1f13d.png)

**Comment by rennera** [comment]
Also - when you right click the file the menu shows up under the News on the side menu.
![image](https://user-images.githubusercontent.com/3689865/104477716-736ade80-558f-11eb-92ff-773d70205ff5.png)

**Comment by blazornut** [comment]
done
