### ISSUE TITLE
NS Section D

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#92]
Qd1
-  Remove Qd1 a-k from validation check (I made this change myself)

Qd1h
- Change qd1h from “language delayed” to “home environment/problems at home” (I made this change myself)
- Change qd1h FRE from “retard de langage” to “milieu familial/problèmes à domicile” (I made this change myself)
- (I added these here because I wanted you to keep track of what changes I have made)

Double-clicking to de-select a response
- Teachers will inevitably select responses they wish to de-select in Qd1a-k

**Comment by rennera** [comment]
This has been completed
