### ISSUE TITLE
NS Section E

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#93]
Qe1
- Change Qe1 question header from “Prior to Primary, did this child:” to “Prior to Primary, did this child receive services from an early intervention program including:”
- Change Qe1 question header from “Avant la maternelle, est-ce que l’enfant…:” to “Avant la maternelle, est-ce que l’enfant a béné_cié des services d’un proframme d’intervention préventive parmi les suivants?”

Qe2
- Change Qe2 question header from “Prior to Primary, did this child:” to “Prior to Primary, did this child attend/was cared for by one or more of the following:”
- Change Qe2 FRE question header from “L'enfant a-t-il déjà participé aux activités? Si oui, à quelle fréquence?” to “Avant la maternelle, est-ce que l’enfant A été accueilli ou pris en charge par l’un ou plusieurs des services suivants?”

**Comment by rennera** [comment]
This has been completed
