### ISSUE TITLE
Section D - Option to deselect in Qd3

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#97]
Can you include a blank response option (or some way for teachers to deselect) for these questions? In the case that teachers accidentally click a response, they are unable to de-select from the drop down menu. 

![image](https://user-images.githubusercontent.com/24963245/107810693-15bae500-6d3b-11eb-8c6d-53c890543b94.png)

**Comment by rennera** [comment]
A null option has been added to the top of drop downs.  When they select this null option it will save a 0 in the database.
